### ISSUE TITLE
The run-time environment settings

### ISSUE THREAD

**Issue by lizhuo-1994** [schatty/EMAC#1]
Hi, could you please share me the environment settings? 
Including cuda version, GPU info, torch version, etc.
I am trying to reproduce your experiment.

Thank for your help!
Bests.

**Comment by schatty** [comment]
Hello, all experiments were obtained with Nvidia GTX 1080ti, CUDA Version: 11.2, Driver Version: 460.39. I added `requirements.txt` for Conda env which should work to the repo's root: 

_libgcc_mutex=0.1=main
_openmp_mutex=4.5=1_gnu
blas=1.0=mkl
ca-certificates=2022.3.29=h06a4308_0
certifi=2021.10.8=py39h06a4308_2
cudatoolkit=11.3.1=h2bc3f7f_2
intel-openmp=2022.0.1=h06a4308_3633
ld_impl_linux-64=2.35.1=h7274673_9
libffi=3.3=he6710b0_2
libgcc-ng=9.3.0=h5101ec6_17
libgomp=9.3.0=h5101ec6_17
libstdcxx-ng=9.3.0=hd4cf53a_17
libuv=1.40.0=h7b6447c_0
mkl=2022.0.1=h06a4308_117
ncurses=6.3=h7f8727e_2
openssl=1.1.1n=h7f8727e_0
pip=21.2.4=py39h06a4308_0
python=3.9.12=h12debd9_0
pytorch=1.11.0=py3.9_cuda11.3_cudnn8.2.0_0
pytorch-mutex=1.0=cuda
readline=8.1.2=h7f8727e_1
setuptools=58.0.4=py39h06a4308_0
sqlite=3.38.2=hc218d9a_0
tk=8.6.11=h1ccaba5_0
typing_extensions=4.1.1=pyh06a4308_0
tzdata=2022a=hda174b7_0
wheel=0.37.1=pyhd3eb1b0_0
xz=5.2.5=h7b6447c_0
zlib=1.2.11=h7f8727e_4

**Comment by lizhuo-1994** [comment]
I appreciate your work EMAC and your open-science style!

BTW, the code is very clear and high-quality!

Github needs more authors like you!

Again, thank you very much!
